export const STEP_TYPE_MAP: Record<number, string> = {
  0: "move",
  1: "dodge",
  2: "damage",
  3: "ball",
  4: "pickup",
  5: "pass",
  6: "block",
  7: "stand_up",
  8: "handoff",
  9: "catch",
  10: "gfi",
  11: "interception",
  12: "landing",
  13: "throw_team_mate",
  14: "follow_up",
  15: "jump_up",
  16: "dauntless",
  17: "leap",
  18: "hypnotic_gaze",
  19: "shadowing",
  20: "tentacles",
  21: "break_tackle",
  22: "pro",
  24: "stab",
  27: "special_skill",
  29: "special_action",
  31: "chainsaw",
  32: "bomb"
};

export const ACTION_CODE_MAP: Record<number, string> = {
  1: "move",
  2: "blitz",
  3: "block",
  4: "pass",
  5: "handoff",
  6: "foul",
  7: "stand_up",
  8: "throw_teammate",
  9: "end_turn",
  10: "use_skill",
  11: "special_move",
  12: "bomb",
  13: "chain_action",
  14: "kick",
  15: "special",
  16: "special"
};

export const ROLL_TYPE_MAP: Record<number, string> = {
  0: "no_roll",
  1: "armor",
  2: "block_dice",
  3: "roll_family_3",
  4: "injury",
  5: "scatter",
  6: "bounce",
  7: "ko_recovery",
  8: "kickoff_scatter",
  9: "kickoff_event",
  10: "armor_chain_check_2d6",
  11: "pickup",
  12: "catch",
  13: "pass",
  14: "handoff",
  15: "landing",
  16: "dauntless",
  17: "wild_animal",
  18: "bone_head_or_really_stupid",
  19: "animal_savagery",
  20: "hypnotic_gaze",
  25: "randomizer_25",
  26: "randomizer_26",
  30: "special_event_30",
  31: "casualty",
  32: "apothecary_or_doctor",
  33: "regeneration_or_resilience",
  34: "foul_armor",
  35: "foul_ejection",
  37: "foul_injury",
  38: "throw_teammate",
  39: "weather",
  40: "kickoff_table",
  41: "regeneration",
  42: "secret_weapon_sent_off",
  43: "apothecary",
  44: "fan_factor_or_prayer",
  45: "weather_or_pitch",
  46: "crowd_surf_injury",
  47: "bounce_or_scatter_chain",
  48: "sweltering_heat",
  49: "special_play_card",
  67: "special_rule",
  68: "prayer_to_nuffle",
  69: "inducement",
  70: "bribe",
  71: "secret_weapon",
  72: "chainsaw",
  73: "bombardier",
  74: "bomb_scatter",
  75: "bomb_catch",
  76: "throw_in",
  87: "randomizer_87",
  88: "special_event_88"
};

export const END_TURN_REASON_MAP: Record<number, string> = {
  0: "unknown_or_setup",
  1: "manual_end",
  2: "turnover",
  3: "forced_end",
  4: "touchdown_or_half_end",
  5: "timer_or_disconnection",
  6: "concession_or_admin_end"
};

export function labelForCode(map: Record<number, string>, code: number | undefined, fallback: string): string {
  if (code === undefined) {
    return fallback;
  }

  return map[code] ?? `${fallback}_unknown_${code}`;
}
